### ISSUE TITLE
6.3 EOL, any plans for T2 mbp kernel v6.4 (or 6.5) ?

### ISSUE THREAD

**Issue by kashortiexda** [t2linux/t2linux-fedora-kernel#8]
With 6.3 nearing/reaching EOL, any plans for T2 mbp kernel v6.4 (or 6.5) ?

**Comment by sharpenedblade** [comment]
> With 6.3 nearing/reaching EOL, any plans for T2 mbp kernel v6.4 (or 6.5) ?

I follow upstream Fedora versions. The current f38 kernel is on 6.3.12, so that is the latest T2 kernel. When Fedora pushes a 6.4 kernel to stable the T2 kernel will be updated within a few days.
